### ISSUE TITLE
Upload to esp32-c3 board

### ISSUE THREAD

**Issue by DRCRecoveryData** [atc1441/ATC_Wifi_Toothbrush#1]
Hi

Could you provide steps and pinout wire to upload to devkit esp32 c3 board and lcd with a virbator to make a clone toothbrush?

**Comment by atc1441** [comment]
Hey, just added it to the repo https://github.com/atc1441/ATC_Wifi_Toothbrush/blob/main/Pinout_ESP32-C3_Toothbrush.jpeg

**Comment by DRCRecoveryData** [comment]
> Hey, just added it to the repo https://github.com/atc1441/ATC_Wifi_Toothbrush/blob/main/Pinout_ESP32-C3_Toothbrush.jpeg

Could you check that does this esp32 c3 have this oled pcb model support on firmware?![image](https://github.com/atc1441/ATC_Wifi_Toothbrush/assets/85211068/4d01246d-1f43-43b6-a221-d1493d23fca9)

Also which is that virbation model from toothbrush?

**Comment by atc1441** [comment]
Hey, its a different pinout of that display.
I would use a seperate one.

The vibration is just one of those flat round vibration thingies
